"""empty message

Revision ID: 795063779006
Revises: 92d65fabef82
Create Date: 2023-05-07 17:59:51.490193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795063779006'
down_revision = '92d65fabef82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['user.id'], name='fk_follows_followee_id'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='fk_follows_follower_id'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(), nullable=True))
        batch_op.drop_column('Linkedln_URL')
        batch_op.drop_column('Facebook_URL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Facebook_URL', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Linkedln_URL', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('facebook')
        batch_op.drop_column('linkedin')

    op.drop_table('follows')
    # ### end Alembic commands ###
